### ISSUE TITLE
Allow to always close a test run

### ISSUE THREAD

**Issue by slavab89** [bahmutov/cypress-testrail-simple#14]
Right now, it seems that it will close a test run only if all tests have been marked as something (Pass/Fail).

Is it possible to introduce a "force close" flag or something similar to always close the run regardless of how many were marked?
The reason for that is that to me, it seems that that particular run is controlled via Cypress. It's Cypress's responsibility so if he opens it, he should be the one to close it

**Comment by samelawrence** [comment]
If we can resolve #24, this issue will effectively go away.
