### ISSUE TITLE
Map all Cypress test states into TestRail status

### ISSUE THREAD

**Issue by DoctorStupidMD** [bahmutov/cypress-testrail-simple#25]
Hi there, 

I'm happy to say that I finally got a (partial) run sent to TestRail! However, I seem to be experiencing the issue that only about 10% of our tests results arrive while the rest remain `Untested`. 

My first thought was this bit of commented-out code in `src/plugin.js`:
```
// TestRail status
          // Passed = 1,
          // Blocked = 2,
          // Untested = 3,
          // Retest = 4,
          // Failed = 5,
          // TODO: map all Cypress test states into TestRail status
```

But, I then looked to our Cypress Dashboard and noticed that: 
- most of our tests had passed,
- the pending ones were set to `Failed` (different issue),
- no other results other than `Passed` or `Failed` had outputted, and
- the test run was unable to close properly (due to the possibly `null` test case results), which also caused the CI build to eventually fail. However, every test in the suite ran successfully before the build fail.

I'd also like to note that the test suite is pretty large, large enough to substantiate our use of 9 parallelised workers in CI. I'm not sure if parallelisation would have anything to do with it.

@bahmutov I'd be very grateful for any insight based on the info provided. Please let me know if I can provide anything else. Thanks!

**Comment by youngha-sung** [comment]
I just created a PR to map the TestRail status with Cypress status which could help a part of the issue. https://github.com/bahmutov/cypress-testrail-simple/pull/38 
@bahmutov Can you review the PR and provide feedback?

**Comment by bahmutov** [comment]
Looking into this. Currently if any of the tests are pending (`it.skip`) they are remaining as "untested" in the TestRail run and it does not close properly

![Screen Shot 2022-04-21 at 11 40 54](https://user-images.githubusercontent.com/2212006/164498746-0f090048-bfdb-47ce-be8c-74f0ff773ee0.png)

**Comment by bahmutov** [comment]
We probably want to mark these tests as "Blocked", then the testrail run closes correctly
