### ISSUE TITLE
Allow to track more than on test id per test

### ISSUE THREAD

**Issue by rbknajera** [bahmutov/cypress-testrail-simple#28]
I currently have several automated tests that covers more than one test case, for those tests only one test id is being tracked, 

Eg: C818 C819 - Verify Edit link in Address section is responsive and directs to correct url

TestRail results in cypress/integration/Features_Tests/My_Account/addressBook.spec.js
┌─────────┬─────────┬───────────┐
│ (index) │ case_id │ status_id │
├─────────┼─────────┼───────────┤
│    0    │   135   │     1     │
│    1    │   818   │     1     │

Only C818 is being updated.

**Comment by samelawrence** [comment]
I can see how this would be convenient as an option, but this is also sort of an anti-pattern. For example, if you have multiple IDs, you'd expect multiple descriptions and parsing those could get buggy. Is there a reason you don't want to merge down your 1st-class tests so they more closely represent your automated workflows? Or break up your automation?

**Comment by samelawrence** [comment]
If it was up to me, I would consolidate the visibility and functionality of a button down to a single test case, but I realize that everyone has their own style for test cases.

**Comment by parul1220** [comment]
I do totally understand that merging the tests would be one way to go, however unfortunately that is not how we manage our manual+automation tests. Is there any plan on implementing this feature.
