### ISSUE TITLE
Add a script to check the test case IDs

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-testrail-simple#42]
If we have a wrong test case ID in the test title, creating a new TestRail run fails. 
TestRail API has a way to get all test case IDs https://www.gurock.com/testrail/docs/api/reference/cases/#getcases
We can add a script to check the test cases for a project

**Comment by jjhelguero** [comment]
On March 31st, the issue was due to a test case being deleted in test rail.
https://github.com/kouzoh/test-framework-cypress/pull/779
