### ISSUE TITLE
TestRail test cases are not getting updated (With allureWriter config)

### ISSUE THREAD

**Issue by kasunalwis** [bahmutov/cypress-testrail-simple#50]
Currently, we are using `[allureWriter](https://www.npmjs.com/package/@shelex/cypress-allure-plugin)` to generate reports after the execution. 

But looks like test cases are never get's updated with the below configs on plugins.index file

<img width="489" alt="Screenshot 2022-05-06 at 22 06 26" src="https://user-images.githubusercontent.com/11239934/167209527-add26997-4552-4a9b-b5bb-45537b843fb9.png">

However, I see it successfully read test rail ID but no logs after that

<img width="723" alt="Screenshot 2022-05-06 at 22 11 33" src="https://user-images.githubusercontent.com/11239934/167210134-82c127fe-fe9c-41fe-8390-542afb894a64.png">

**Comment by Farhaz12** [comment]
Same Problem I am facing !

**Comment by bahmutov** [comment]
Unfortunately I am not using Allure reporter, so cannot say what is happening. If anyone has any guesses, I hope they can answer. I would also look at the verbose debugging logs, maybe there is something in them (if you enable vs disable the Allure report plugin) https://github.com/bahmutov/cypress-testrail-simple#debugging

**Comment by kasunalwis** [comment]
I just found out that we need to set `allureReuseAfterSpec: true` in env variables so both plugins can work together. Closing the issue since its resolved
