### ISSUE TITLE
Testrail test cases are not getting updated and the run isn't closing.

### ISSUE THREAD

**Issue by brunomarcall** [bahmutov/cypress-testrail-simple#52]
I'm trying to create a CI script that integrates Cypress with Testrail. I was using this repository as a base, but I identified a problem in the execution of the script:
The run is created in testrail, but after running the Cypress tests, the result is not added to the run and it is not closed.

- When running the code with the environment variable DEBUG=cypress-testrail-simple I got the following return:
![issue_1](https://user-images.githubusercontent.com/53955930/167743870-15e5452e-2c3a-4dd7-b3d8-53e8c5d292c3.png)

- I decided to analyze the logs of this repository, and I noticed that the last times the script was executed it had the same problem I'm facing, however, as the tests pass the script doesn't show any problem, even not adding the results to the testrail nor closing the run:
![issue_2](https://user-images.githubusercontent.com/53955930/167743903-f18afa56-e2de-45b1-b27d-9da9bd04094a.png)

So I believe that something can be done to correct this behavior.

**Comment by bahmutov** [comment]
Have you tried to turn on debugging logs? See https://github.com/bahmutov/cypress-testrail-simple#debugging how to see them

**Comment by brunomarcall** [comment]
131 / 5.000
Yes, actually I'm always running the script with the environment variable for DEBUG. Here are the prints with more details in the logs:

- The screenshots below show the logs for the step of closing the run. (I just censored the information regarding the host and user for security):
    - Part 1
![issue_3](https://user-images.githubusercontent.com/53955930/167960319-2ad4b225-6a6e-4c2c-bc31-9c99d0b0253c.png)
    - Part 2
![issue_4](https://user-images.githubusercontent.com/53955930/167960337-1fbbd1e3-30b6-4d87-8e5b-d7cd76417c4d.png)

I couldn't identify what might be going wrong, but even after the tests are run, the result is not added to the Tetrail.

**Comment by bahmutov** [comment]
Does it send the test status to test rail while Cypress runs?

**Comment by brunomarcall** [comment]
I don't think so, is there any way to check this?

**Comment by bahmutov** [comment]
Did you add this plugin to your Cypress plugins file? See https://github.com/bahmutov/cypress-testrail-simple#install and the example plugin https://github.com/bahmutov/test-rail-example/blob/main/cypress/plugins/index.js#L24 If you used DEBUG environment variable while running Cypress tests you should see messages about sending the status of the finished tests

**Comment by brunomarcall** [comment]
Yes, the plugin is configured in the cypress plugins file. Here's the image:
![issue_5](https://user-images.githubusercontent.com/53955930/168120284-306a2c93-b88f-4763-94d5-46e1670b6943.png)

- Can you show me an example of a log that proves the sending of statuses?
- Are these statuses what actually ensure the result is added to the testrail?

**Comment by brunomarcall** [comment]
I made the fix you showed and now it works. Thanks a lot for the help!!
![image](https://user-images.githubusercontent.com/53955930/168152782-f40a8653-d94d-4379-9f62-bf23b51cf14a.png)
![image](https://user-images.githubusercontent.com/53955930/168152943-7f5d4adc-2b25-4638-85e0-88a8c26957b5.png)
