### ISSUE TITLE
Cypress 10 / TestRail 

### ISSUE THREAD

**Issue by jamiesheehan** [bahmutov/cypress-testrail-simple#57]
Just a quick question on Cypress 10 and TestRail are they compatible and if so do I set these in the cypress.env.json file or elsewhere?: 

```
  "TESTRAIL_HOST": "hosturl",
  "TESTRAIL_USERNAME": "yourtestraillogin",
  "TESTRAIL_PASSWORD": "testrailAPIKEY",
  "TESTRAIL_PROJECTID": "PROJECTID" 
```

Running with the above config in the cypress.env.json file results in : 

```
npx testrail-start-run
\node_modules\cypress-testrail-simple\src\get-config.js:27
    throw new Error('TESTRAIL_HOST is required')
```

**Comment by bahmutov** [comment]
These variables are _operating system_ environment variables. You would set them using the OS way before running Cypress. For example, on Linux/Mac you would do
```
TESTRAIL_USERNAME=abc TESTRAIL_PASSWORD=123 ... npx cypress run
```

Tip: since these values should be secret, I recommend using https://github.com/bahmutov/as-a utility
