### ISSUE TITLE
TESTRAIL_HOST required but is already added in Cypress.json

### ISSUE THREAD

**Issue by mikzerafa** [bahmutov/cypress-testrail-simple#60]
![277_TestRailHost](https://user-images.githubusercontent.com/19959516/181017137-25925e43-8f2a-41e0-96e0-3f75d4fe8c86.png)
![278_Error](https://user-images.githubusercontent.com/19959516/181017304-c06d8f86-9a67-418b-b8c1-37d8f6762a21.png)

I am running npx testrail-run-start
and I am getting the error above.

I have set the env variables but for some reason it is still giving me the same error.

**Comment by bahmutov** [comment]
Nope, these variables must be the process (OS) environment variables, not Cypress ones. See https://github.com/bahmutov/cypress-testrail-simple#environment-variables Tip: I would not put them into cypress.json because they are sensitive variables

**Comment by mikzerafa** [comment]
Thank you Gleb!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
