### ISSUE TITLE
Running any script returns ERR_INVALID_URL

### ISSUE THREAD

**Issue by ArnesMehinovic** [bahmutov/cypress-testrail-simple#65]
When running any of the scripts (ex. ` testrail-check-case-ids`), all I get is ERR_INVALID_URL.

I am trying to set up this locally, so I am passing all the env vars as directly into terminal. 
Example: `TESTRAIL_HOST=MYDOMAIN.testrail.com TESTRAIL_USERNAME=myuser@mydomain.com TESTRAIL_PASSWORD=TestRailApiKey TESTRAIL_PROJECTID=3 TESTRAIL_RUN_ID=61 npx testrail-check-case-ids`

I can see that input is a valid URL -> myhost.testrail.com/index.php?/api/v2/get_cases/3&limit=200' but then code is ERR_INVALID_URL.

Can you provide your help on this @bahmutov?

**Comment by bahmutov** [comment]
does your `TESTRAIL_HOST` start with `https://`?

**Comment by ArnesMehinovic** [comment]
No, it's literally name.testrail.com
